spring.application.name=enterprise

# Configuração de conexão com Oracle XE com Spring Data JPA apontado para o Pluggable Database (XEPDB1)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=${ERP_DB_USER}
spring.datasource.password=${ERP_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuração do Hibernate/JPA com ddl-auto: update para criação de tabelas de forma automática
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect